@startuml
class Utilisateur {
  +id: int
  +nom_complet: str
  +email: str
  +telephone: str
  +type_utilisateur: str
  +role: Rôle
  +mot_de_passe_hash: str
  +est_suspendu: bool
  +raison_suspension: str
  +origine_suspension: OrigineSuspension
  +date_suspension: date
}

enum Rôle {
  administrateur
  adhérent
}

enum OrigineSuspension {
  automatique
  manuelle
}

class Livre {
  +id: int
  +titre: str
  +auteur: str
  +isbn: str
  +editeur: str
  +annee_publication: int
  +nombre_exemplaires: int
  +exemplaires_disponibles: int
}

class DemandeEmprunt {
  +id: int
  +date_demande: date
  +statut: StatutDemandeEmprunt
}

enum StatutDemandeEmprunt {
  en_attente
  approuvée
  rejetée
}

class Emprunt {
  +id: int
  +date_emprunt: date
  +date_limite: date
  +date_retour: date
}

class Réservation {
  +id: int
  +date_reservation: date
  +statut: StatutRéservation
}

enum StatutRéservation {
  active
  clôturée
}

Utilisateur "1" -- "0..*" DemandeEmprunt
Livre "1" -- "0..*" DemandeEmprunt
Utilisateur "1" -- "0..*" Emprunt
Livre "1" -- "0..*" Emprunt
Utilisateur "1" -- "0..*" Réservation
Livre "1" -- "0..*" Réservation

DemandeEmprunt ..> Emprunt : approuvée -> créer emprunt
Emprunt ..> Utilisateur : en retard -> suspension automatique
@enduml
