@startuml
actor Bibliothecaire
participant UI
participant "ServiceRetour" as S
database DB

Bibliothecaire -> UI : enregistrer retour
UI -> S : retourner(empruntId)
S -> DB : maj date_retour_reelle + statut
S -> S : calculerRetard()
alt retard > 0
  S -> DB : creer Penalite
end
S -> DB : incrementer stock ouvrage
S --> UI : retour validé
@enduml
